import CartIcon from './IconCart.vue'
import EmptyStarIcon from './IconEmptyStar.vue'
import FilledStarIcon from './IconFilledStar.vue'
import HalfStarIcon from './IconHalfStar.vue'
import MenuIcon from './IconMenu.vue'
import SadIcon from './IconSad.vue'
import TrashIcon from './IconTrash.vue'
import ArrowUpIcon from './IconArrowUp.vue'
import ArrowDownIcon from './IconArrowDown.vue'
export {CartIcon, EmptyStarIcon, FilledStarIcon, HalfStarIcon, MenuIcon, SadIcon, TrashIcon, ArrowUpIcon, ArrowDownIcon}